### ISSUE TITLE
Feature Request: Work with the Adafruit nrf52840 Express

### ISSUE THREAD

**Issue by gallaugher** [MajicDesigns/MD_Cubo#10]
I'm using a jolliCube + the library works great with an Arduino Uno. Thank you. I've sent in a contribution.
I'd love to adapt this to work with the Adafruit Feather nrf52840 Express, which would allow me to easily add Bluetooth from Adafruit's iOS and Android Bluefruit app.

I've connected the Adafruit board & the test sketch runs fine, but when running the the MD_Cubo_Demo_V1_0, I get the errors below. FYI: The wiring on the Adafruit board is:
M0 instead of Pin 11 on the Uno and
SK instead of Pin 13 on the Uno

Errors are as follows:
====================================
Arduino: 1.8.10 (Mac OS X), Board: "Adafruit Bluefruit Feather nRF52840 Express, 0.2.13 SoftDevice s140 6.1.1, Level 0 (Release)"

/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp: In member function 'virtual void MD_Cubo_ICS574::begin()':
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:19:3: error: 'DDRC' was not declared in this scope
   DDRC = 0xff;
   ^~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:19:3: note: suggested alternative: 'DEC'
   DDRC = 0xff;
   ^~~~
   DEC
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:20:3: error: 'PORTC' was not declared in this scope
   PORTC = 0x00;
   ^~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:23:3: error: 'TCCR2A' was not declared in this scope
   TCCR2A = 0x00;
   ^~~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:24:3: error: 'TCCR2B' was not declared in this scope
   TCCR2B = 0x00;
   ^~~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:25:22: error: 'WGM21' was not declared in this scope
   TCCR2A |= (0x01 << WGM21); // CTC mode. clear counter on TCNT2 == OCR2A
                      ^~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:26:3: error: 'OCR2A' was not declared in this scope
   OCR2A = 10; // Interrupt every 25600th cpu cycle (256*100)
   ^~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:27:3: error: 'TCNT2' was not declared in this scope
   TCNT2 = 0x00; // start counting at 0
   ^~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:27:3: note: suggested alternative: 'SCNd32'
   TCNT2 = 0x00; // start counting at 0
   ^~~~~
   SCNd32
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:28:22: error: 'CS22' was not declared in this scope
   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler
                      ^~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:28:22: note: suggested alternative: 'CHG2'
   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler
                      ^~~~
                      CHG2
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:28:39: error: 'CS21' was not declared in this scope
   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler
                                       ^~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:28:39: note: suggested alternative: 'CHG1'
   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler
                                       ^~~~
                                       CHG1
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:29:3: error: 'TIMSK2' was not declared in this scope
   TIMSK2 |= (0x01 << OCIE2A);
   ^~~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:29:22: error: 'OCIE2A' was not declared in this scope
   TIMSK2 |= (0x01 << OCIE2A);
                      ^~~~~~
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp: At global scope:
/Users/gallaugh/Documents/Arduino/libraries/MD_Cubo/src/MD_Cubo_8x8_ICS574.cpp:66:4: error: expected constructor, destructor, or type conversion before '(' token
 ISR(TIMER2_COMPA_vect)
    ^
Multiple libraries were found for "SoftwareSerial.h"
 Used: /Users/gallaugh/Library/Arduino15/packages/adafruit/hardware/nrf52/0.15.1/libraries/SoftwareSerial
Multiple libraries were found for "MD_Cubo.h"
 Used: /Users/gallaugh/Documents/Arduino/libraries/MD_Cubo
exit status 1
Error compiling for board Adafruit Bluefruit Feather nRF52840 Express.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by MajicDesigns** [comment]
It seems that the IDE/compiler is just including all the header files whether they are needed or not.
The errors are due to the AVR assembler code that is in the hardware drivers for the MD_Cubo_8x8_ICS574. You have 2 options for fixing this:

1. Edit the MD_Cubo_8x8_ICS574.cpp file and comment out all the code in the begin() and ISR() functions. As you are not using this type of cube not having the code there will make no difference, but it will stop the compiler trying to process this AVR assembler code.

2. Delete the files and change the library header not to include the (now missing) header file. In fact, if all you want is jolliCube, you can just delete everything else and leave the JC files only, changing all relevant references to the other cbe types. This takes a bit more work and knowledge.

Longer term the AVR code should be in #defines based on architecture, but a lot of the code for this library is contributed by others ...

**Comment by gallaugher** [comment]
Wonderful. Almost there. I used option #1 and commented out the begin() and ISR() in MD_Cubo_8x8_ICS574.cpp
I also needed to modify MD_Cubo_8x8_jC.h as follows to conform with Adafruit nrf52840 Feather:
const uint8_t DATA = MOSI;  ///< SPI Data pin number
const uint8_t CLK  = SCK;  ///< SPI Clock pin number

There seems to be something still missing in the MD_Cubo libraries to get things working with the nrf52840, though. When I run this demo the jolliCube folks put on their MD_Cubo instructable:
https://sites.google.com/site/jollifactory/jolliCube_MD_Cubo_Demo_V1_0.zip?attredirects=0&d=1
The first animations that don't use MD_Cubo all work fine, but once things hit the MD_Cubo animations, then the cube doesn't behave as expected. When the loop returns back to the non MD_Cubo definitions, by that time only the front plane of LED lights works. Any thoughts on what I should update? Thanks!

**Comment by MajicDesigns** [comment]
> The first animations that don't use MD_Cubo all work fine

They all appear to us MD_Cubo so I am not sure what you mean. Please be more specific.  From what I can see the animations are selected at random, so your comment in this context does not make sense to me.

> Any thoughts on what I should update?

No idea as I don't know your hardware. Maybe try running the animations in a different order and see if the problem persists in the same 'slot' (ie, 2nd or 3rd, or whatever) or whether it is tied to a particular animation. This may give a clue. The Jollicube guys write the demo using some of my code, so I am not that familiar with their stuff.

**Comment by gallaugher** [comment]
Hi, The demo in the URL above is from the jolliCube Google Drive & has the animations segmented as follows, and the animation fail happens after the second commented section that refers to these as being from the MD_Cubo library:

    //Animation effects adapted from other LED cube projects    
    fireworks,
    effect_bitmapspinSequence1,
    recedingText,
    scrollingText,
    effect_path_bitmapSequence1,
    wormsqueeze,
    CornerToCorner,
    effect_bitmapspinSequence2,
    effect_path_bitmapSequence2,

    //Animation effects from MD_Cubo library     
    oscillation, 
    firefly, 
    intersectPlanes, 
    brownian, 
    ripples, 
    outsideStack, 
    //recedingText, 
    rain, 
    shrinkCube, 
    randomFill, 
    flagwave, 
    slideFaces, 
    hourglass, 
    //scrollingText, 
    wrapFaces, 
    suspension, 
    spiralLine, 
    boingCube, 
    droplets    

This sketch also has a RANDOM_CYCLES flag that's initially set to false (0), so these go through in the order listed above. 
Here's that URL:
https://sites.google.com/site/jollifactory/jolliCube_MD_Cubo_Demo_V1_0.zip?attredirects=0&d=1

The Adafruit nrf52840 Feather is supposed to be fully Arduino compatible, but the pin settings for MOSI and SCK differ. Switching the settings as mentioned above worked for the first set of animations that are allegedly not MD_Cubo, so I was hopeful there might be some obvious setting I could tweak to get the rest of the MD_Cubo settings inline. Again, library works wonderfully for the Uno. Thanks for your work!

**Comment by MajicDesigns** [comment]
The animations being MD_Cubo or not simply seems to refer to whether they were sourced from my original demo or the JC guys did them (recedingText and scrollingText were 'MD_Cubo' but moved from the lower block to the upper block).

If the fail is at 'oscillation', then comment that out and see if that single animation is the problem, etc. You could also try commenting out the JC animations at the start and see if the others run ok. Basically it is a matter of testing where the sensitivity for this fault is - time related, code related, etc.

Is it possible that your hardware implements a Watch Dog Timer that somehow resets the machine? Or that other background tasks are using the SPI interface as well?
