### ISSUE TITLE
Error compiling, file not found,  {Case sensitive filename in Linux}

### ISSUE THREAD

**Issue by Travesty42** [MajicDesigns/MD_Cubo#13]
## IMPORTANT
Before submitting this issue
[x ] Have you tried using the latest version of the library?
[ ] Have you checked this has not already been submitted and/or resolved?
[ ] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
Compile issue using MD_Cubo_4x4_ICS595.h 
## Your Environment
**Library Version:** 2.1.0
**Arduino IDE version:**  1.8.15
**Hardware model/type:** Arduino Uno
**OS and Version:** LinuxLite

## Steps to Reproduce
run Test or Demo, mark correct board "MD_Cubo_4x4_ICS595.h" , upload, errors out : file MD_CUBO_4x4_ICS595.h not found

## Expected Behaviour
compile properly

## Actual Behaviour
MD_Cubo_4x4_ICS595.cpp references MD_CUBO_4x4_ICS595.h, but title is "MD_Cubo_4x4_ICS595.h" in Linux, file names are case sensitive. renamed reference in CPP file and it compiled fine.

## Code Demonstrating the Issue
````
Insert your code here.
````

**Comment by MajicDesigns** [comment]
Fixed and released as v2.1.1
