### ISSUE TITLE
Demo animation OutsideStack crashing

### ISSUE THREAD

**Issue by c-schmitz** [MajicDesigns/MD_Cubo#3]
When running the function OutsideStack from the demo file the Arduino is crashing for some reason.
All other demo animations work fine.

**Comment by c-schmitz** [comment]
Seems to work now.

**Comment by c-schmitz** [comment]
@MajicDesigns Actually I think there might an error within some of the other cubes.

Where it says

  if ((x > CUBE_SIZE) || (y > CUBE_SIZE) || (z > CUBE_SIZE))

shouldn't it rather be 

  if ((x > CUBE_SIZE-1) || (y > CUBE_SIZE-1) || (z > CUBE_SIZE-1))

I fixed this for the STC cube and that might have fixed the OutsideStack crash.

**Comment by c-schmitz** [comment]
@MajicDesigns Actually I think there might an error within some of the other cubes.

Where it says
`
  if ((x > CUBE_SIZE) || (y > CUBE_SIZE) || (z > CUBE_SIZE))
`
shouldn't it rather be 

`  if ((x > CUBE_SIZE-1) || (y > CUBE_SIZE-1) || (z > CUBE_SIZE-1))`

I fixed this for the STC cube and that might have fixed the OutsideStack crash.

**Comment by MajicDesigns** [comment]
Agree should be ">= CUBE_SIZE" or "> CUBE_SIZE-1". Changes pushed to repo.

**Comment by c-schmitz** [comment]
Guess this can be closed then.
