### ISSUE TITLE
The library seem not working with my 4x4x4 Led Cube based on ICS595.

### ISSUE THREAD

**Issue by Wooopz** [MajicDesigns/MD_Cubo#7]
Hello,

I'm trying to run your library MD_Cubo_Demo with my ics595-type card (ICStation 4X4X4 Light Cube Kit).

I removed the comment in front of #include "MD_Cubo_4x4_ICS595.h".
The code compiles and loads correctly in my Arduino Uno but nothing happens.
My LED Cube remains silent and displays nothing.
I tested my Led Cube and it works properly with the provided library.
Could you help me please ?

Thanks you

**Comment by MajicDesigns** [comment]
Did you comment out the other header files, leaving only the ICS595 header?
What debugging have you already tried?
Which sketch are you trying to run?

**Comment by Wooopz** [comment]
I leaving only ICS595 header.
For debugging, i try :
 - enable DEBUG,
 - change LAYER_TIME (5 to 10) in MD_Cubo_4x4_ICS595.h
- change Arduino Uno card
I trying to run Demo and Test sketchs.
The Serial output send me information but no led on cube.
My Led Cube working good with the code from https://emalliab.wordpress.com/tag/icstation/.

**Comment by Wooopz** [comment]
Leaving only ICS595.
I try to

**Comment by MajicDesigns** [comment]
I'll need to set up and test. This could take a while.

**Comment by Wooopz** [comment]
ok. Thank you

**Comment by MajicDesigns** [comment]
Fixed. Version 2.0.1 uploaded. Please remember that you cannot have debug turned on with this cube as the SPI lines used for the 595  (pins 0, 1, 2) are the same as the standard hardware serial port.
