### ISSUE TITLE
Build error ATmega32U4

### ISSUE THREAD

**Issue by loefstrand** [MajicDesigns/MD_Cubo#9]
Hi!

I get a build error when trying to build the jolliCude_MD_Cubo_Demo_V1_0-sketch with an Arduino Micro / Leonardo or any board with A Atmega32U4 on.

I get the following error:

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/USBAPI.h:44:0,

                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:233,

                 from sketch\jolliCube_MD_Cubo_Demo_V1_0.ino.cpp:1:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/USBCore.h:82:48: error: expected unqualified-id before numeric constant

 #define TEST_MODE                              3

                                                ^

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src/MD_Cubo_8x8_jC.h:73:15: note: in expansion of macro 'TEST_MODE'

 const uint8_t TEST_MODE   = 0x0F; ///< MAX7219 test mode control register address

               ^~~~~~~~~

Multiple libraries were found for "MD_Cubo.h"
 Used: C:\Users\lond\Documents\Arduino\libraries\MD_Cubo
Multiple libraries were found for "SoftwareSerial.h"
 Used: C:\Program
 Not used: C:\Users\lond\Documents\Arduino\libraries\EspSoftwareSerial
exit status 1
Error compiling for board Arduino/Genuino Micro.

I have the following setup:
Arduino IDE - 1.8.10
MD_Cubo - 2.0.2
Custom Arduino Micro board

/// Marcus

**Comment by loefstrand** [comment]
If I comment out "#define TEST_MODE 3" from "USBCore.h" then I get the following results:

Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Micro"

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp: In member function 'virtual void MD_Cubo_ICS574::begin()':

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:23:3: error: 'TCCR2A' was not declared in this scope

   TCCR2A = 0x00;

   ^~~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:23:3: note: suggested alternative: 'TCCR0A'

   TCCR2A = 0x00;

   ^~~~~~

   TCCR0A

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:24:3: error: 'TCCR2B' was not declared in this scope

   TCCR2B = 0x00;

   ^~~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:24:3: note: suggested alternative: 'TCCR0B'

   TCCR2B = 0x00;

   ^~~~~~

   TCCR0B

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:25:22: error: 'WGM21' was not declared in this scope

   TCCR2A |= (0x01 << WGM21); // CTC mode. clear counter on TCNT2 == OCR2A

                      ^~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:25:22: note: suggested alternative: 'WGM41'

   TCCR2A |= (0x01 << WGM21); // CTC mode. clear counter on TCNT2 == OCR2A

                      ^~~~~

                      WGM41

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:26:3: error: 'OCR2A' was not declared in this scope

   OCR2A = 10; // Interrupt every 25600th cpu cycle (256*100)

   ^~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:26:3: note: suggested alternative: 'OCR3A'

   OCR2A = 10; // Interrupt every 25600th cpu cycle (256*100)

   ^~~~~

   OCR3A

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:27:3: error: 'TCNT2' was not declared in this scope

   TCNT2 = 0x00; // start counting at 0

   ^~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:27:3: note: suggested alternative: 'TCNT0'

   TCNT2 = 0x00; // start counting at 0

   ^~~~~

   TCNT0

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:28:22: error: 'CS22' was not declared in this scope

   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler

                      ^~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:28:22: note: suggested alternative: 'CS12'

   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler

                      ^~~~

                      CS12

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:28:39: error: 'CS21' was not declared in this scope

   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler

                                       ^~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:28:39: note: suggested alternative: 'CS01'

   TCCR2B |= (0x01 << CS22) | (0x01 << CS21); // Start the clock with a 256 prescaler

                                       ^~~~

                                       CS01

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:29:3: error: 'TIMSK2' was not declared in this scope

   TIMSK2 |= (0x01 << OCIE2A);

   ^~~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:29:3: note: suggested alternative: 'TIMSK0'

   TIMSK2 |= (0x01 << OCIE2A);

   ^~~~~~

   TIMSK0

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:29:22: error: 'OCIE2A' was not declared in this scope

   TIMSK2 |= (0x01 << OCIE2A);

                      ^~~~~~

C:\Users\lond\Documents\Arduino\libraries\MD_Cubo\src\MD_Cubo_8x8_ICS574.cpp:29:22: note: suggested alternative: 'OCIE0A'

   TIMSK2 |= (0x01 << OCIE2A);

                      ^~~~~~

                      OCIE0A

Multiple libraries were found for "MD_Cubo.h"
 Used: C:\Users\lond\Documents\Arduino\libraries\MD_Cubo
Multiple libraries were found for "SoftwareSerial.h"
 Used: C:\Program
 Not used: C:\Users\lond\Documents\Arduino\libraries\EspSoftwareSerial
exit status 1
Error compiling for board Arduino/Genuino Micro.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

After removing all the settings files, except for the JC from the src-folder and changed the SPI-pins in the MD_Cubo_8x8_jC.h-file, I finally is able to build and load the µP. :) :)

/// Marcus

**Comment by MajicDesigns** [comment]
The issue is caused by the define TEST_MODE being defined in both the MD_Cubo library (specific for JolliCube class) and the users's other included library (USBCore).

TEST_MODE is defined and used once only in the JC files, so the easiest user fix is to rename this in the JC header file and the JC code file to something different (eg, TEST_MODE_JC).

As this issue is very specific and affects a very small subset of users, affected users should implement the workaround above.
